#!/bin/bash

# stop on first failure
set -e

# show each command
set -x

# link dirs and files to laptop setup
ln -sf /home/"$USER"/setup/legion-y530/etc /home/"$USER"/etc
ln -sf /home/"$USER"/setup/legion-y530/bin /home/"$USER"/bin
ln -sf /home/"$USER"/setup/legion-y530/.bash_aliases /home/"$USER"/.bash_aliases
ln -sf /home/"$USER"/setup/legion-y530/.bash_custom /home/"$USER"/.bash_custom
ln -sf /home/"$USER"/setup/legion-y530/.emacs /home/"$USER"/.emacs
ln -sf /home/"$USER"/setup/legion-y530/.gitconfig /home/"$USER"/.gitconfig
ln -sf /home/"$USER"/setup/legion-y530/.gitconfig-account /home/"$USER"/.gitconfig-account
ln -sf /home/"$USER"/setup/legion-y530/.gitconfig-account-gmail /home/"$USER"/.gitconfig-account-gmail
ln -sf /home/"$USER"/setup/legion-y530/.docker/config.json /home/"$USER"/.docker/config.json

# install lightdm configuration
ln -sf /home/"$USER"/etc/lightdm/lightdm.conf /etc/lightdm/lightdm.conf
ln -sf /home/"$USER"/bin/screen-layout /usr/local/bin/screen-layout

# symlinks for net configuration
ln -sf /home/"$USER"/bin/net_eth /usr/local/bin/net_eth
ln -sf /home/"$USER"/bin/net_wifi /usr/local/bin/net_wifi

# add user to some groups
usermod -aG docker "$USER"
usermod -aG dialout "$USER"

# sudoers config to preserve some environemnt variables
cp /home/"$USER"/etc/sudoers.d/nopasswd /etc/sudoers.d/env
chmod 440 /etc/sudoers.d/env

# sudoers config to not require password for some commands
cp /home/"$USER"/etc/sudoers.d/nopasswd /etc/sudoers.d/nopasswd
chmod 440 /etc/sudoers.d/nopasswd

# install some tools
apt install picocom tree

# regenerate initramfs to renaming network interface have effect
# then reboot
update-initramfs -u
