#!/bin/bash

# stop on first failure
set -e

# show each command
set -x

# link dirs and files to laptop setup
ln -sf /home/"$SUDO_USER"/setup/legion-y530/etc /home/"$SUDO_USER"/etc
ln -sf /home/"$SUDO_USER"/setup/legion-y530/bin /home/"$SUDO_USER"/bin
ln -sf /home/"$SUDO_USER"/setup/legion-y530/.bash_aliases /home/"$SUDO_USER"/.bash_aliases
ln -sf /home/"$SUDO_USER"/setup/legion-y530/.bash_custom /home/"$SUDO_USER"/.bash_custom
ln -sf /home/"$SUDO_USER"/setup/legion-y530/.emacs /home/"$SUDO_USER"/.emacs
ln -sf /home/"$SUDO_USER"/setup/legion-y530/.gitconfig /home/"$SUDO_USER"/.gitconfig
ln -sf /home/"$SUDO_USER"/setup/legion-y530/.gitconfig-account /home/"$SUDO_USER"/.gitconfig-account
ln -sf /home/"$SUDO_USER"/setup/legion-y530/.gitconfig-account-gmail /home/"$SUDO_USER"/.gitconfig-account-gmail
ln -sf /home/"$SUDO_USER"/setup/legion-y530/.docker/config.json /home/"$SUDO_USER"/.docker/config.json

# link dirs and files to laptop setup
# this files may be overwritten
ln -sf /home/"$SUDO_USER"/setup/legion-y530/.config/lxpanel/Lubuntu/panels/panel /home/"$SUDO_USER"/.config/lxpanel/Lubuntu/panels/panel
ln -sf /home/"$SUDO_USER"/setup/legion-y530/.config/lxterminal/lxterminal.conf /home/"$SUDO_USER"/.config/lxterminal/lxterminal.conf

# install lightdm configuration
ln -sf /home/"$SUDO_USER"/etc/lightdm/lightdm.conf /etc/lightdm/lightdm.conf
ln -sf /home/"$SUDO_USER"/bin/screen-layout /usr/local/bin/screen-layout

# symlinks for net configuration
ln -sf /home/"$SUDO_USER"/bin/net_eth /usr/local/bin/net_eth
ln -sf /home/"$SUDO_USER"/bin/net_wifi /usr/local/bin/net_wifi

# symlinks for dns
ln -sf /home/"$SUDO_USER"/etc/resolv.conf.9.9.9.9 /etc/resolv.conf.9.9.9.9
ln -sf /home/"$SUDO_USER"/etc/resolv.conf.systemd /etc/resolv.conf.systemd

# add user to some groups
usermod -aG docker "$SUDO_USER"
usermod -aG dialout "$SUDO_USER"

# sudoers config to preserve some environemnt variables
cp /home/"$SUDO_USER"/etc/sudoers.d/nopasswd /etc/sudoers.d/env
chmod 440 /etc/sudoers.d/env

# sudoers config to not require password for some commands
cp /home/"$SUDO_USER"/etc/sudoers.d/nopasswd /etc/sudoers.d/nopasswd
chmod 440 /etc/sudoers.d/nopasswd

# install some tools
apt install picocom tree

# regenerate initramfs to renaming network interface have effect
# then reboot
update-initramfs -u
