#!/bin/bash

# Install some custom configuratation for openwrt switch

# Stop on first failure
set -e

# Show each command
set -x

# Directories to install on openwrt switch
dirs="etc/ usr/"

# Go to script directory
cd "$(dirname "$0")"

# Use default access values if not specified
[ -z "openwrt_ip" ] || openwrt_ip=192.168.1.1
[ -z "openwrt_user" ] || openwrt_user=root

# Add private ssh key
ssh-copy-id "$openwrt_user@$openwrt_ip"

`# Create local archive of needed directories` \
tar cf - $dirs |
`# Connect to openwrt switch and unpack archive to overwrite default configs with custom ones` \
ssh "$openwrt_user@$openwrt_ip" "
    tar x -C / -f -
"

# TODO manually
# * passwd
# * Set credentials for uddns in file /etc/config/uddns
