#!/bin/bash

# stop on first failure
set -e

# show each command
set -x

# link dirs and files to laptop setup
ln -sf /root/setup/linksys-wrd3600/etc /root/etc

# symlinks for dns client config
# ln -sf /root/etc/resolv.conf.9.9.9.9 /etc/resolv.conf.9.9.9.9

# symlink for dhcp and dns server config
ln -sf /root/etc/dnsmasq.conf /etc/dnsmasq.conf

# symlink for hardcoded assignment between hostnames and ip addresses
ln -sf /root/etc/hosts /etc/hosts

# symlinks for uddns service to run at startup
ln -s /etc/init.d/uddns /etc/rc.d/S97uddns
ln -s /etc/init.d/uddns /etc/rc.d/K97uddns
